# Generated by Django 4.2.1 on 2023-09-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_giveaway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='cover_image',
            new_name='name',
        ),
    ]
