# Generated by Django 4.2.1 on 2023-09-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_giveaway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='book_covers/'),
            preserve_default=False,
        ),
    ]
