# Generated by Django 4.2.5 on 2023-09-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_giveaway', '0002_rename_cover_book_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(null=True),
        ),
    ]
