# Generated by Django 4.2.1 on 2023-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_giveaway', '0003_remove_book_genre_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='media/book_covers/'),
        ),
    ]
